name = "radish-stew"
main = "src/index.js"
compatibility_date = "2024-04-05"

[triggers]
crons = ["37 15 * * *"] # * * * * * = run every minute

[vars]
MISSKEY_INSTANCE = ""
MISSKEY_KEY = ""
MISSKEY_USERID = ""
# INSERT YOUR MESSAGE HERE
# MESSAGE = ""
VIEWRANGE = "Follower"
